# Warmup Plots of the Data Set

```{r prepare-data, echo=TRUE, message=TRUE, warning=TRUE, dev='svg'}
# load libraries, the data, and prepare it
if (Sys.getenv("RSTUDIO") == "1") { 
  if (Sys.getenv("LOGNAME") == "smarr") {
    setwd("/Users/smarr/Collab/Richard-Roberts/AliveTyping/evaluation") } }

source("scripts/libraries.R", chdir=TRUE)
data_2 <- select(load_data_file("007-6484e45d-others.data.bz2"),
                 c("Value", "Unit", "Benchmark", "VM", "Iteration"))
data_2 <- filter(data_2, VM != "Higgs" & VM != "SOMns")
data_4 <- select(load_data_file("010-f8d6ca79-moth.data.bz2"),
                 c("Value", "Unit", "Benchmark", "VM", "Iteration"))
data_5 <- select(load_data_file("012-df5b8bfd-higgs.data.bz2"),
                 c("Value", "Unit", "Benchmark", "VM", "Iteration"))


data <- rbind(
  data_2, data_4, data_5
)
data <- prepare_vm_names(data)

summary(data)

warmup_plot <- function (data_b, b) {
  ## First take the medians over the values for each VM separated
  medians <- ddply(data_b, ~ VM, summarise,
             median = median(Value))
  # use the highest one with a little margin as an upper bound
  upperBound <- 2 * max(medians$median)
  data_b <- ddply(data_b, ~ Benchmark, here(transform),
                  ValCut = pmin(Value, upperBound))

  plot <- ggplot(data_b, aes(x=Iteration, y=ValCut))
  plot <- plot + geom_line(aes(colour = VM))
  plot <- plot + ggtitle(b)
  plot <- plot + scale_x_continuous(breaks = seq(0, max(data_b$Iteration), 100))
  plot <- plot + geom_vline(xintercept = c(100, 200, 300), linetype = "longdash", colour = "#cccccc")
  plot <- plot + theme_simple()
  print(plot)
}
```

# Plots

```{r warmup-plots, echo=FALSE, dev='png', fig.keep='all', fig.width=10, fig.height=6}
# b <- "Mandelbrot"

for (b in levels(data$Benchmark)) {
  data_b <- droplevels(subset(data, Benchmark == b))
  warmup_plot(data_b, b)
}
```
