all:
	pdflatex artifact
	#bibtex artifact
	pdflatex artifact
	pdflatex artifact

clean:
	$(RM) *.log *.aux \
	*.cfg *.glo *.idx *.toc *.vtc \
	*.ilg *.ind *.out *.lof \
	*.lot *.bbl *.blg *.gls *.cut *.hd \
	*.dvi *.ps *.thm *.tgz *.zip *.rpi \
	*.synctex.gz *.fdb_latexmk *.fls .*.lb \
	artifact.pdf
